'use client';

import React, { useState } from 'react';
import { Sparkles, Bot, AlertTriangle, Send, Cpu, CheckCircle2 } from 'lucide-react';
import { apiRequest } from '@/lib/api-client';

export function GrcIntelligenceView() {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<any | null>(null);

  const handleAssistSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setLoading(true);
    try {
      const data = await apiRequest('/intelligence/assist', {
        method: 'POST',
        body: JSON.stringify({ prompt: prompt.trim() }),
      });
      setResponse(data);
    } catch (err: any) {
      alert(err.message || 'Error executing AI assistance query.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 py-6 omni-fade-in space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 pb-5">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-teal-700" />
            <h1 className="text-xl sm:text-2xl font-bold text-slate-900">GRC Intelligence Surface</h1>
          </div>
          <p className="text-xs sm:text-sm text-slate-600 mt-1">
            LLM-powered compliance advisory, control mapping recommendations, and gap analysis assistance.
          </p>
        </div>
      </div>

      {/* Mandatory Disclaimer Banner */}
      <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-amber-900 text-xs flex items-start gap-3 shadow-sm">
        <AlertTriangle className="w-4 h-4 text-amber-700 flex-shrink-0 mt-0.5" />
        <div>
          <span className="font-bold text-amber-900">AI Assistance Disclaimer:</span> Outputs generated by GRC Intelligence provide contextual advisory suggestions to assist human auditors. They do not constitute authoritative compliance or legal determinations.
        </div>
      </div>

      {/* Query Form */}
      <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-sm space-y-4">
        <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
          <Bot className="w-5 h-5 text-teal-700" /> Ask GRC Intelligence
        </h3>
        <form onSubmit={handleAssistSubmit} className="space-y-3">
          <textarea
            rows={4}
            placeholder="e.g., Recommend ISO 27001 and SOC 2 clauses for our data encryption at rest control, or request gap analysis..."
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            className="w-full px-4 py-3 text-sm bg-white border border-slate-300 rounded-xl text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-1 focus:ring-teal-600 transition font-medium"
          />
          <div className="flex justify-between items-center">
            <div className="text-xs text-slate-600 font-medium flex items-center gap-2">
              <Cpu className="w-3.5 h-3.5 text-slate-500" /> Router: Tier 1 (Gemini) / Tier 2 (Claude 3.5)
            </div>
            <button
              type="submit"
              disabled={loading || !prompt.trim()}
              className="inline-flex items-center gap-2 px-5 py-2 text-sm font-semibold rounded-xl bg-teal-700 hover:bg-teal-800 text-white shadow-sm disabled:opacity-50 transition"
            >
              <Send className="w-4 h-4" /> {loading ? 'Analyzing...' : 'Generate Guidance'}
            </button>
          </div>
        </form>
      </div>

      {/* Response Display */}
      {response && (
        <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-sm space-y-5 omni-fade-in">
          <div className="flex items-center justify-between border-b border-slate-200 pb-3">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-700" />
              <h4 className="text-base font-bold text-slate-900">AI Advisory Suggestions</h4>
            </div>
            <span className="text-xs font-mono font-bold px-2.5 py-0.5 rounded bg-slate-100 text-teal-800 border border-slate-200">
              Tier: {response.tierUsed}
            </span>
          </div>

          <div className="text-xs font-medium text-amber-900 bg-amber-50 p-3 rounded-lg border border-amber-200">
            {response.disclaimer}
          </div>

          {response.suggestions && response.suggestions.length > 0 ? (
            <div className="space-y-3">
              <h5 className="text-xs font-bold text-slate-700 uppercase tracking-wider">Suggested Clause Mappings</h5>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {response.suggestions.map((s: any, idx: number) => (
                  <div key={idx} className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                    <div className="flex justify-between items-center">
                      <span className="font-mono text-xs font-bold text-teal-800 bg-teal-100 px-2 py-0.5 rounded border border-teal-200">{s.clauseCode}</span>
                      <span className="text-xs font-semibold text-slate-600">Score: {(s.confidenceScore * 100).toFixed(0)}%</span>
                    </div>
                    <div className="text-xs font-bold text-slate-800 mt-1">{s.frameworkCode}</div>
                    {s.reasoning && <div className="text-xs text-slate-600 mt-1 font-medium">{s.reasoning}</div>}
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="text-sm text-slate-600 font-medium">Analysis completed. No direct clause mappings were triggered for this prompt.</div>
          )}
        </div>
      )}
    </div>
  );
}
