'use client';

import React, { useState } from 'react';
import { Sparkles, Bot, AlertTriangle, Send, Cpu, CheckCircle2, Shield } from 'lucide-react';

export function GrcIntelligenceView() {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<any | null>(null);

  const handleAssistSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setLoading(true);
    try {
      const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null;
      const res = await fetch('/api/intelligence/assist', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: token ? `Bearer ${token}` : '',
        },
        body: JSON.stringify({ prompt: prompt.trim() }),
      });

      if (!res.ok) throw new Error('AI Intelligence request failed.');
      const data = await res.json();
      setResponse(data);
    } catch (err: any) {
      alert(err.message || 'Error executing AI assistance query.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-cyan-400" /> GRC Intelligence Surface
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            LLM-powered compliance advisory, control mapping recommendations, and gap analysis assistance.
          </p>
        </div>
      </div>

      {/* Mandatory Disclaimer Banner */}
      <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-300 text-xs flex items-start gap-3">
        <AlertTriangle className="w-4 h-4 text-amber-400 flex-shrink-0 mt-0.5" />
        <div>
          <span className="font-semibold text-amber-200">AI Assistance Disclaimer:</span> Outputs generated by GRC Intelligence provide contextual advisory suggestions to assist human auditors. They do not constitute authoritative compliance or legal determinations.
        </div>
      </div>

      {/* Query Form */}
      <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-4">
        <h3 className="text-base font-bold text-white flex items-center gap-2">
          <Bot className="w-5 h-5 text-cyan-400" /> Ask GRC Intelligence
        </h3>
        <form onSubmit={handleAssistSubmit} className="space-y-3">
          <textarea
            rows={4}
            placeholder="e.g., Recommend ISO 27001 and SOC 2 clauses for our data encryption at rest control, or request gap analysis..."
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            className="w-full px-4 py-3 text-sm bg-slate-950 border border-slate-800 rounded-xl text-slate-200 placeholder-slate-500 focus:outline-none focus:border-cyan-500 transition"
          />
          <div className="flex justify-between items-center">
            <div className="text-xs text-slate-500 flex items-center gap-2">
              <Cpu className="w-3.5 h-3.5 text-slate-400" /> Router: Tier 1 (Gemini) / Tier 2 (Claude 3.5)
            </div>
            <button
              type="submit"
              disabled={loading || !prompt.trim()}
              className="inline-flex items-center gap-2 px-5 py-2 text-sm font-semibold rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white shadow-lg shadow-cyan-600/20 disabled:opacity-50 transition"
            >
              <Send className="w-4 h-4" /> {loading ? 'Analyzing...' : 'Generate Guidance'}
            </button>
          </div>
        </form>
      </div>

      {/* Response Display */}
      {response && (
        <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-5 animate-fadeIn">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-400" />
              <h4 className="text-base font-bold text-white">AI Advisory Suggestions</h4>
            </div>
            <span className="text-xs font-mono font-medium px-2.5 py-0.5 rounded bg-slate-800 text-cyan-400 border border-slate-700">
              Tier: {response.tierUsed}
            </span>
          </div>

          <div className="text-xs text-amber-400 bg-amber-500/10 p-3 rounded-lg border border-amber-500/20">
            {response.disclaimer}
          </div>

          {response.suggestions && response.suggestions.length > 0 ? (
            <div className="space-y-3">
              <h5 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Suggested Clause Mappings</h5>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {response.suggestions.map((s: any, idx: number) => (
                  <div key={idx} className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
                    <div className="flex justify-between items-center">
                      <span className="font-mono text-xs font-bold text-cyan-400">{s.clauseCode}</span>
                      <span className="text-xs text-slate-400">Score: {(s.confidenceScore * 100).toFixed(0)}%</span>
                    </div>
                    <div className="text-xs text-slate-300 font-medium">{s.frameworkCode}</div>
                    {s.reasoning && <div className="text-xs text-slate-400 mt-1">{s.reasoning}</div>}
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="text-sm text-slate-400">Analysis completed. No direct clause mappings were triggered for this prompt.</div>
          )}
        </div>
      )}
    </div>
  );
}
