-- CreateEnum
CREATE TYPE "ApprovalPurpose" AS ENUM ('POLICY_APPROVAL', 'POLICY_EXCEPTION', 'RISK_ACCEPTANCE', 'RISK_TREATMENT', 'CONTROL_SIGNOFF', 'FINDING_VERIFICATION', 'FINDING_CLOSURE', 'VENDOR_ASSESSMENT', 'VULNERABILITY_REMEDIATION', 'VULNERABILITY_RISK_ACCEPTANCE', 'INCIDENT_RESOLUTION', 'INCIDENT_CLOSURE', 'EVIDENCE_VERIFICATION');

-- AlterTable
ALTER TABLE "approval_instances" ADD COLUMN "purpose" "ApprovalPurpose";
